### ISSUE TITLE
Missing <use> element

### ISSUE THREAD

**Issue by ptvirgo** [JordanMartinez/purescript-halogen-svg-elems#28]
Noticed that you didn't have the <use> element, which would be nice to have so that icons and such could be incorporated from svg images instead of requiring hand-coding directly in Purescript.

I took a stab at it myself, but it does not work as expected:
https://github.com/ptvirgo/purescript-halogen-svg-elems/compare/master...ptvirgo:use

Somehow that results in <use> elements being created, but not rendered by the browser.  Would be interested to help if I can.

**Comment by ptvirgo** [comment]
Are you opposed to adding the `<use>` element?

**Comment by JordanMartinez** [comment]
No. Are there reasons why I might want to not add it here?

**Comment by ptvirgo** [comment]
I hope not!  What would be helpful?

**Comment by JordanMartinez** [comment]
I don't use Halogen at work, and I'm focusing on other things in the community right now. So, I guess a PR?

**Comment by ptvirgo** [comment]
Sounds like you've got a competing for your attention, and maybe supporting this project makes for a lot of extra work. Wouldn't want to put you in a bad spot.

How can I get from my "probably almost working" version to one that actually does work?

**Comment by ptvirgo** [comment]
Looks like you think this is a waste of your time.

**Comment by JordanMartinez** [comment]
My lack of response after only two days should not be interpreted as that. A week? Maybe, but even then you could phrase that comment as a question.

The first thing I would check is the HTML produced when halogen renders the code. What does the browser's HTML inspector show? Is the tag included at all? Does it contain weird stuff that confuses the browser?

I would then use a print-based debugging approach by adding `spy`s at various places to see where and whether things are being called. Are things work as expected? Also, since this is a fork, one thing I still don't understand is why this library uses a different [`element`](https://pursuit.purescript.org/packages/purescript-halogen-svg-elems/4.0.0/docs/Halogen.Svg.Core#v:element) than Halogen's [`element`](https://pursuit.purescript.org/packages/purescript-halogen/6.1.2/docs/Halogen.HTML.Core#v:element).

Third, I'd ask on the Discord channel to see if anyone else can provide help.

Fourth, you could make it easier for me to debug this alongside of you by providing a gist that can be used in Try PureScript. Since `halogen` and this library are in the package set, you should be able to write the code you've added here into that gist inline and then use halogen there to see what happens. That saves me time because I don't have to clone your PR and set up the necessary stuff to render a page using Halogen.

**Comment by ptvirgo** [comment]
Ah - sorry!  So give it a week and phrase comments as questions?

**Comment by JordanMartinez** [comment]
Yeah.

Also, here's how I read the opening comment for this issue. 
> Hey we should also add 'use' to this library at some point. I've done some work here but it doesn't work yet. (implied but not said directly: I might figure out how to fix it myself, but if I don't, maybe someone can build off of it and get it working. Either way, this does not need to be done immediately. Just at some point in the future, I hope to see this supported)

That's why I responded the way I did [here](https://github.com/JordanMartinez/purescript-halogen-svg-elems/issues/28#issuecomment-918561104). In other words, I won't be spending time on adding this, but I hope you figure it out and then submit a PR that adds that. If you have questions like this one, "How can I get from my "probably almost working" version to one that actually does work?", then I can provide some ideas for how to make it work (like the 4 suggestions above). But at the end of the day, this is not my priority.

My current priority is implementing targets for Spago, and then helping out with the Registry work, which are arguably more important for the community as a whole than this one issue.

**Comment by JordanMartinez** [comment]
Closed by 42f93f6655a3f1a47c0550ba592c49703caf63e1

@ptvirgo I changed your usage of `xlink:href` to `href`. Apparently, that is [deprecated per MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)

**Comment by JordanMartinez** [comment]
I know I said I wasn't going to work on this, but then my Spago PRs haven't gotten feedback yet because Fabrizio has a busy week and I didn't want to get too involved in Registry stuff until my Spago PRs got done. So, this seemed like the next best thing to fix.
