### ISSUE TITLE
SVG animation `repeatCount` should accept "indefinite"

### ISSUE THREAD

**Issue by liammcdermott** [JordanMartinez/purescript-halogen-svg-elems#37]
`Halogen.Svg.Attributes.repeatCount`, for making SVG animations repeat, only accepts an Int value.

See:
https://github.com/JordanMartinez/purescript-halogen-svg-elems/blob/master/src/Halogen/Svg/Attributes.purs#L262

However, [according to MDN it may also have the value "indefinite"](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/repeatCount), which makes the animation continue forever. I'm thinking that many people (if not most) making an SVG animation will want it to repeat indefinitely, so Halogen SVG should support that.

Thanks for the hard work on this library, it's great! :+1:

**Comment by JordanMartinez** [comment]
Care to submit a PR? We'll need to change that to a `String` and release this as a breaking change

**Comment by liammcdermott** [comment]
Sure, I can submit a PR. I have a question though. I was thinking of creating a new type to handle this case, something like:

`
data RepeatCount  = Definite Int | Indefinite
`

Then the `Show` instance for that type could generate a value that makes sense for the `repeatCount` SVG attribute. And the question: is there enough value in typing this, or is it just better to make the attribute a `String`?

**Comment by JordanMartinez** [comment]
While I appreciate the idea above, the issue is that it'll require a breaking change if we ever need to add a new value due to a spec change (e.g. pattern matching would no longer be exhaustive if a new data constructor was added).

The HTML DSL exposed both here and in Halogen tends not to care as much about type safety as it could. Those that want to use `repeatCount` likely know what the syntax accepts. If one wanted to define a more type-safe DSL, this is likely not the library on which to do it.

I would appreciate a library that does use type-safety to enforce always-correct HTML, but I'm sure the initial cost and maintenance burden is high.

**Comment by liammcdermott** [comment]
> The HTML DSL exposed both here and in Halogen tends not to care as much about type safety as it could. Those that want to use repeatCount likely know what the syntax accepts. If one wanted to define a more type-safe DSL, this is likely not the library on which to do it.

Understood, this makes sense. Thank you very much for the explanation, I genuinely wasn't sure of the best way to approach the problem, which is why I asked!

**Comment by liammcdermott** [comment]
Thanks for merging that PR @JordanMartinez! :+1:  I'm assuming it's okay to close this issue now.
